language: node_js
services:
    - postgresql
node_js:
    - "6"
install: npm install
before_script: 
    - psql -c 'create database testgraph;' -U postgres & node server/index.js & node db/database.js & grunt build
notifications:
  slack: 
    rooms:
      - hr46:bSjNxkQB9ai5NmnKnQKyYtCW#truncated-avocados
